name: webapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  http: ^1.2.0
  flutter:
    sdk: flutter

  google_fonts: ^6.1.0
  supabase_flutter: ^2.3.4

  cupertino_icons: ^1.0.8
  dart_openai: ^5.1.0
  lucide_icons: ^0.257.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

